### ISSUE TITLE
Problem with the example of AWGN Simulation 

### ISSUE THREAD

**Issue by emozo** [bastibl/gr-ieee802-11#121]
Hello Bastian, I want to run the AWGN simulation like you suggest in the wimex-project page. I am using the master branch, 3.7.12 version of Gnuradio and I haven´t modified any fiel. When I  excute the
sudo make  in the command line, I have the following problem. Could you suggest me any thing about this problem ? Thank you in abvance

erislandy@erislandy-HP-ProBook-450-G4:~/prefix/src/gr-ieee-80211/simulations/awgn$ sudo make
results/sim_0_0_1.0_.pcap
mkdir -p results
export GR_CONF_DEFAULT_MAX_MESSAGES=123
REPETITION=0
ENCODING=0
SNR=1.0
 ./sim.py --messages=100 --encoding=0 --snr=1.0 --repetition=0
Traceback (most recent call last):
  File "./sim.py", line 18, in <module> from gnuradio import analog
  File "/home/erislandy/prefix/lib/python2.7/dist-packages/gnuradio/analog/__init__.py", line 33, in <module> from analog_swig import *
  File "/home/erislandy/prefix/lib/python2.7/dist-packages/gnuradio/analog/analog_swig.py", line 28, in <module>_analog_swig = swig_import_helper()
  File "/home/erislandy/prefix/lib/python2.7/dist-packages/gnuradio/analog/analog_swig.py", line 24, in swig_import_helper_mod = imp.load_module('_analog_swig', fp, pathname, description)
ImportError: libgnuradio-analog-3.7.12.0.so.0.0.0: cannot open shared object file: No such file or directory
Makefile:19: fallo en las instrucciones para el objetivo 'results/sim_0_0_1.0_.pcap'
make: *** [results/sim_0_0_1.0_.pcap] Error 1

**Comment by bastibl** [comment]
The error that you experience is not related to this project. It is an issue with your GNU Radio installation (or your pybombs environment is not loaded or set up correctly).
Some unrelated tips: don't run this as root (there is really no reason for that). If you have problems that the simulations do not terminate, use the `next` branch of GNU Radio. It contains fixes for the GNU Radio runtime.
