### ISSUE TITLE
name 'ieee802_11' is not defined

### ISSUE THREAD

**Issue by xmpuri** [bastibl/gr-ieee802-11#214]
Hi @bastibl I got this error when I ran `examples/wifi_loopback.grc`:
```
gnuradio-companion
<<< Welcome to GNU Radio Companion 3.9.0.0-git >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/home/user/gr-ieee802-11/examples/wifi_loopback.grc"
>>> Loading: /home/user/gr-ieee802-11/examples/wifi_phy_hier.grc
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block chan_est
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'ieee802_11' is not defined
ERROR:gnuradio.grc.core.FlowGraph:Failed to evaluate parameter block encoding
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gnuradio/grc/core/FlowGraph.py", line 246, in renew_namespace
    value = eval(parameter_block.params['value'].to_code(), namespace)
  File "<string>", line 1, in <module>
NameError: name 'ieee802_11' is not defined
...
>>> Load Error: /home/manoj/gr-ieee802-11/examples/wifi_phy_hier.grc: Flowgraph invalid
```

I've set my CMAKE_INSTALL_PREFIX as in #192 
Is there anything else you would recommend doing?
I saw #193 but I'm not necessarily sure where or what to set the LD_LIBRARY_PATH or LIBRARY_PATH. How would you do this?
Thanks for your help!

**Comment by bastibl** [comment]
Please see this instructions:
https://www.wime-project.net/installation/
Or the GNU Radio Wiki:
https://wiki.gnuradio.org/index.php/ModuleNotFoundError
