### ISSUE TITLE
AttributeError: module 'ieee802_11' has no attribute 'LS'

### ISSUE THREAD

**Issue by ilyasbsran** [bastibl/gr-ieee802-11#268]
GNU Radio Companion => 3.8.2.0
Python  => 3.6.9
Ubunutu => 18.04
cmake => 3.20.1
Hi, 
When i execute wifi_rx.grc example, i get this error.
```
Generating: '/home/ilyas/gr-ieee802-11/examples/wifi_rx.py'

Executing: /usr/bin/python3 -u /home/ilyas/gr-ieee802-11/examples/wifi_rx.py

linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "/home/ilyas/gr-ieee802-11/examples/wifi_rx.py", line 412, in <module>
    main()
  File "/home/ilyas/gr-ieee802-11/examples/wifi_rx.py", line 388, in main
    tb = top_block_cls()
  File "/home/ilyas/gr-ieee802-11/examples/wifi_rx.py", line 143, in __init__
    self._chan_est_options = [ieee802_11.LS, ieee802_11.LMS, ieee802_11.STA, ieee802_11.COMB]
AttributeError: module 'ieee802_11' has no attribute 'LS'

>>> Done (return code 1)
```
```
(base) ilyas@ilyas:~/gr-ieee802-11/build$ cmake ..
-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found LOG4CPP: /usr/local/lib/liblog4cpp.so
CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (GMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/FindGMP.cmake:1 (include)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/FindMPLIB.cmake:1 (find_package)
  /usr/local/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:26 (find_dependency)
  CMakeLists.txt:84 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gmp'
--   Found gmp, version 6.2.1
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (MPIR).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/FindMPIR.cmake:1 (include)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/FindMPLIB.cmake:2 (find_package)
  /usr/local/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:26 (find_dependency)
  CMakeLists.txt:84 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.65.1") found components: date_time program_options filesystem system regex thread unit_test_framework chrono atomic 
-- Found Volk: Volk::volk  
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable exact version "3.6.9") 
CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (FFTW3f).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPkgConfig.cmake:70 (find_package_handle_standard_args)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/FindFFTW3f.cmake:6 (INCLUDE)
  /usr/local/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/gnuradio-fftConfig.cmake:24 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:116 (include)
  CMakeLists.txt:84 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.7
-- Found FFTW3f: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Found Git: /usr/bin/git  
-- Extracting version information from git describe...
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Using install prefix: /usr/local
-- Building for version: e2a59771 / 1.1.0git
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found SWIG: /usr/bin/swig3.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ilyas/gr-ieee802-11/build
`
`(base) ilyas@ilyas:~/gr-ieee802-11/build$ make
[  3%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/chunks_to_symbols_impl.cc.o
[  7%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/constellations_impl.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/decode_mac.cc.o
[ 14%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/equalizer/base.cc.o
[ 18%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/equalizer/comb.cc.o
[ 22%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/equalizer/ls.cc.o
[ 25%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/equalizer/lms.cc.o
[ 29%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/equalizer/sta.cc.o
[ 33%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/ether_encap_impl.cc.o
[ 37%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/frame_equalizer_impl.cc.o
[ 40%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/mac.cc.o
[ 44%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/mapper.cc.o
[ 48%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/parse_mac.cc.o
[ 51%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/signal_field_impl.cc.o
[ 55%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/sync_long.cc.o
[ 59%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/sync_short.cc.o
[ 62%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/utils.cc.o
[ 66%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/viterbi_decoder/base.cc.o
[ 70%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/viterbi_decoder/viterbi_decoder_x86.cc.o
[ 74%] Linking CXX shared library libgnuradio-ieee802_11.so
[ 74%] Built target gnuradio-ieee802_11
[ 74%] Built target ieee802_11_swig_swig_doc
Scanning dependencies of target ieee802_11_swig_swig_compilation
[ 77%] Swig source ieee802_11_swig.i
[ 77%] Built target ieee802_11_swig_swig_compilation
[ 81%] Building CXX object swig/CMakeFiles/ieee802_11_swig.dir/CMakeFiles/ieee802_11_swig.dir/ieee802_11_swigPYTHON_wrap.cxx.o
[ 85%] Linking CXX shared module _ieee802_11_swig.so
[ 85%] Built target ieee802_11_swig
[ 88%] Generating ieee802_11_swig.pyc
[ 92%] Generating ieee802_11_swig.pyo
[ 92%] Built target pygen_swig_f4cb5
[ 96%] Generating __init__.pyc, utils.pyc
[100%] Generating __init__.pyo, utils.pyo
[100%] Built target pygen_python_eaa3a
```

**Comment by bastibl** [comment]
There are two issues for the exact same error. Please check them. If you still have problems, add the output of the install command and your configuration for your environment variables.
