### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by CKWJustin** [bastibl/gr-ieee802-11#415]
Please advise on how to fix this. Using GNU radio Release v3.10.11.0.

```

Loading: "/home/kali/gr-ieee802-11/examples/wifi_tx.grc"
>>> Done

Generating: "/home/kali/gr-ieee802-11/examples/wifi_tx.py"

Executing: /usr/bin/python3 -u /home/kali/gr-ieee802-11/examples/wifi_tx.py

Traceback (most recent call last):
  File "/home/kali/gr-ieee802-11/examples/wifi_tx.py", line 24, in get_state_directory
    log.warn(f"Found persistent state path '{newpath}', but file does not exist. " +
    ^^^
NameError: name 'log' is not defined

During handling of the above exception, another exception occurred:
 

Traceback (most recent call last):
  File "/home/kali/gr-ieee802-11/examples/wifi_tx.py", line 47, in <module>
    sys.path.append(os.environ.get('GRC_HIER_PATH', get_state_directory()))
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/gr-ieee802-11/examples/wifi_tx.py", line 33, in get_state_directory
    log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio." +
    ^^^
NameError: name 'log' is not defined

>>> Done (return code 1)

```

**Comment by bastibl** [comment]
I think this is (was?) a GNU Radio bug. The current 3.10.11 version on Arch sets this line as 
```python
sys.path.append(os.environ.get('GRC_HIER_PATH', os.path.expanduser('~/.grc_gnuradio')))
```
But also with this old behavior hier blocks are still broken on 3.10.11, because they are no longer stored in `~/.grc_gnuradio` :-)
You'd have to manually set `GRC_HIER_PATH`, see https://github.com/gnuradio/gnuradio/pull/7454
